In [455]:
# kerakli kutubxonalar preprocessing u-n
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

In [456]:
# datasetni import qilib olish
df = pd.read_csv("imdb_top_1000.csv")

In [457]:
# dataset haqida ma'lumot olish
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Poster_Link    1000 non-null   str
 1   Series_Title   1000 non-null   str
 2   Released_Year  1000 non-null   str
 3   Certificate    899 non-null    str
 4   Runtime        1000 non-null   str
 5   Genre          1000 non-null   str
 6   IMDB_Rating    1000 non-null   float64
 7   Overview       1000 non-null   str
 8   Meta_score     843 non-null    float64
 9   Director       1000 non-null   str
 10  Star1          1000 non-null   str
 11  Star2          1000 non-null   str
 12  Star3          1000 non-null   str
 13  Star4          1000 non-null   str
 14  No_of_Votes    1000 non-null   int64
 15  Gross          831 non-null    str
dtypes: float64(2), int64(1), str(13)
memory usage: 125.1 KB

In [458]:
# tushub qolgan qiymatlarni ko'rish 
df.isnull().sum()

Poster_Link        0
Series_Title       0
Released_Year      0
Certificate      101
Runtime            0
Genre              0
IMDB_Rating        0
Overview           0
Meta_score       157
Director           0
Star1              0
Star2              0
Star3              0
Star4              0
No_of_Votes        0
Gross            169
dtype: int64

In [459]:
# bu 3ta f modelimiz uchun foydasiz bolgani u tashlab yuboramiz 
df.drop(['Poster_Link', 'Series_Title', 'Overview'], axis=1, inplace=True)

In [460]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Released_Year  1000 non-null   str
 1   Certificate    899 non-null    str
 2   Runtime        1000 non-null   str
 3   Genre          1000 non-null   str
 4   IMDB_Rating    1000 non-null   float64
 5   Meta_score     843 non-null    float64
 6   Director       1000 non-null   str
 7   Star1          1000 non-null   str
 8   Star2          1000 non-null   str
 9   Star3          1000 non-null   str
 10  Star4          1000 non-null   str
 11  No_of_Votes    1000 non-null   int64
 12  Gross          831 non-null    str
dtypes: float64(2), int64(1), str(10)
memory usage: 101.7 KB

In [461]:
# float ga o'tkazish
df['Gross'] = df['Gross'].str.replace(',', '').astype(float)

In [462]:
# tushub qolgan qiymatlaarni toldirish
df['Meta_score'] = df['Meta_score'].fillna(df['Meta_score'].mean())
df['Gross'] = df['Gross'].fillna(df['Gross'].mean())
df['Certificate'] = df['Certificate'].fillna(df['Certificate'].mode()[0])
df['Runtime'] = df['Runtime'].str.replace(' min', '').astype(int)

In [463]:
df.isnull().sum()

Released_Year    0
Certificate      0
Runtime          0
Genre            0
IMDB_Rating      0
Meta_score       0
Director         0
Star1            0
Star2            0
Star3            0
Star4            0
No_of_Votes      0
Gross            0
dtype: int64

In [464]:
# columns ni ma'lumotlarini ichki tarafdan ko'rish 
df.sample(15)

,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
244,2000,A,154,"Drama, Thriller",8.1,83.00000,Alejandro G. Iñárritu,Emilio Echevarría,Gael García Bernal,Goya Toledo,Álvaro Guerrero,223741,5.383834e+06
724,2017,R,104,"Horror, Mystery, Thriller",7.7,85.00000,Jordan Peele,Daniel Kaluuya,Allison Williams,Bradley Whitford,Catherine Keener,492851,1.760407e+08
593,2013,R,123,"Comedy, Drama, Fantasy",7.8,55.00000,Richard Curtis,Domhnall Gleeson,Rachel McAdams,Bill Nighy,Lydia Wilson,303032,1.532292e+07
727,2014,R,86,"Comedy, Horror",7.7,76.00000,Jemaine Clement,Taika Waititi,Jemaine Clement,Taika Waititi,Cori Gonzalez-Macuer,157498,3.333000e+06
850,1973,A,102,"Action, Crime, Drama",7.7,83.00000,Robert Clouse,Bruce Lee,John Saxon,Jim Kelly,Ahna Capri,96561,2.500000e+07
809,1997,A,127,"Biography, Crime, Drama",7.7,76.00000,Mike Newell,Al Pacino,Johnny Depp,Michael Madsen,Bruno Kirby,279318,4.190976e+07
725,2018,UA,147,"Action, Adventure, Thriller",7.7,86.00000,Christopher McQuarrie,Tom Cruise,Henry Cavill,Ving Rhames,Simon Pegg,291257,2.201591e+08
298,1960,Passed,128,"Biography, Drama, History",8.1,75.00000,Stanley Kramer,Spencer Tracy,Fredric March,Gene Kelly,Dick York,27254,6.803475e+07
66,2008,U,98,"Animation, Adventure, Family",8.4,95.00000,Andrew Stanton,Ben Burtt,Elissa Knight,Jeff Garlin,Fred Willard,999790,2.238082e+08
304,1957,PG,161,"Adventure, Drama, War",8.1,87.00000,David Lean,William Holden,Alec Guinness,Jack Hawkins,Sessue Hayakawa,203463,4.490800e+07
522,1993,A,94,"Animation, Action, Adventure",7.9,77.97153,Yoshiaki Kawajiri,Kôichi Yamadera,Emi Shinohara,Takeshi Aono,Osamu Saka,34529,6.803475e+07
468,2016,UA,100,Drama,7.9,78.00000,Ken Loach,Laura Obiols,Dave Johns,Hayley Squires,Sharon Percy,53818,2.581680e+05
664,1993,R,121,"Crime, Drama, Romance",7.8,80.00000,Robert De Niro,Robert De Niro,Chazz Palminteri,Lillo Brancato,Francis Capra,128171,1.726697e+07
326,2015,UA,159,"Action, Crime, Thriller",8.0,77.97153,Neeraj Pandey,Akshay Kumar,Danny Denzongpa,Rana Daggubati,Taapsee Pannu,52848,6.803475e+07
209,2014,UA,99,"Adventure, Comedy, Crime",8.1,88.00000,Wes Anderson,Ralph Fiennes,F. Murray Abraham,Mathieu Amalric,Adrien Brody,707630,5.910032e+07

# Preprocessing

In [465]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler

class Datapreprocessing:
    def __init__(self, df):
        self.df = df.copy()
    
    # Handle missing values
    def tozala(self):
        for col in self.df.columns:
            if self.df[col].isnull().any():
                if self.df[col].dtype == 'str':
                    self.df[col].fillna(self.df[col].mode()[0], inplace=True)
                else:
                    self.df[col].fillna(self.df[col].mean(), inplace=True)
        return self
    
    # Encode categorical variables
    def encodla(self):
        encoder = LabelEncoder()
        for col in self.df.columns:
            if self.df[col].dtype == 'str':
                if self.df[col].nunique() <= 5:  # few categories → OneHot
                    dummies = pd.get_dummies(self.df[col], prefix=col, dtype=int)
                    self.df = pd.concat([self.df.drop(columns=[col]), dummies], axis=1)
                else:  # many categories → Label Encoding
                    self.df[col] = encoder.fit_transform(self.df[col])
        return self
    
    # Scale numeric features
    def scale_qil(self):
        scaler = MinMaxScaler()
        num_cols = self.df.select_dtypes(include=['int64', 'float64']).columns
        self.df[num_cols] = scaler.fit_transform(self.df[num_cols])
        return self
    
    # Log transformation for skewed features
    def log_transform(self, threshold=0.5):
        skewness = self.df.skew()
        features_log = skewness[(skewness >= threshold)].index.tolist()
        
        for col in features_log:
            if (self.df[col] > 0).all():  # only positive values
                self.df[col] = np.log1p(self.df[col])
        return self

In [466]:
processor = Datapreprocessing(df)

df_ready = (
    processor
    .tozala()
    .encodla()
    .scale_qil()
    .df
)

print(df_ready.head())

   Released_Year  Certificate   Runtime     Genre  IMDB_Rating  Meta_score  \
0       0.727273     0.066667  0.351449  0.681592     1.000000    0.722222
1       0.505051     0.066667  0.471014  0.606965     0.941176    1.000000
2       0.868687     0.933333  0.387681  0.109453     0.823529    0.777778
3       0.525253     0.066667  0.568841  0.606965     0.823529    0.861111
4       0.353535     0.800000  0.184783  0.606965     0.823529    0.944444

   Director     Star1     Star2     Star3     Star4  No_of_Votes     Gross
0  0.257770  0.908953  0.676190  0.100000  0.972281     1.000000  0.030257
1  0.250457  0.632777  0.010714  0.377528  0.206823     0.688207  0.144092
2  0.151737  0.194234  0.336905  0.001124  0.660981     0.982797  0.571025
3  0.250457  0.013657  0.782143  0.791011  0.206823     0.476641  0.061173
4  0.833638  0.382398  0.552381  0.601124  0.448827     0.286778  0.004653

In [467]:
# codni call qilish 
df = encoding(df)
df

,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,72,1,142,137,9.3,80.0,141,599,568,89,912,2343110,2.834147e+07
1,50,1,175,122,9.2,100.0,137,417,9,336,194,1620367,1.349664e+08
2,86,14,152,22,9.0,84.0,83,128,283,1,620,2303232,5.348584e+08
3,52,1,202,122,9.0,90.0,137,9,657,704,194,1129952,5.730000e+07
4,35,12,96,122,9.0,96.0,456,252,464,535,421,689845,4.360000e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,39,1,115,105,7.6,76.0,50,50,260,633,114,166544,6.803475e+07
996,34,3,201,184,7.6,84.0,164,185,668,337,134,34075,6.803475e+07
997,31,7,118,175,7.6,85.0,145,96,566,185,212,43374,3.050000e+07
998,22,12,97,182,7.6,78.0,22,588,392,867,908,26471,6.803475e+07
999,13,12,86,135,7.6,93.0,22,515,487,510,294,51853,6.803475e+07

In [468]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Released_Year  1000 non-null   int64
 1   Certificate    1000 non-null   int64
 2   Runtime        1000 non-null   int64
 3   Genre          1000 non-null   int64
 4   IMDB_Rating    1000 non-null   float64
 5   Meta_score     1000 non-null   float64
 6   Director       1000 non-null   int64
 7   Star1          1000 non-null   int64
 8   Star2          1000 non-null   int64
 9   Star3          1000 non-null   int64
 10  Star4          1000 non-null   int64
 11  No_of_Votes    1000 non-null   int64
 12  Gross          1000 non-null   float64
dtypes: float64(3), int64(10)
memory usage: 101.7 KB

# Filter methot

In [469]:
import numpy as np
# corralation filter ishlatilgan holda 
corr_matrix = df.corr().abs()
upper = corr_matrix.where(np.triu(np.ones(corr_matrix.shape), k=1).astype(bool))
to_drop = [col for col in upper.columns if any(upper[col] > 0.8)]
df_filtered = df.drop(columns=to_drop)
print("\nOriginal shape:", df.shape)
print("Shape after dropping correlated features:", df_filtered.shape)

Original shape: (1000, 13)
Shape after dropping correlated features: (1000, 13)

# Preprocessing bo'lgan datasetni preprocessed papkaga joylash

In [470]:
import os

# Papka yaratish (agar mavjud bo'lmasa)
os.makedirs("preprocessed", exist_ok=True)

# Saqlash
df.to_csv("preprocessed/imdb_top_1000.csv", index=False)

print("preprocessed/imdb_top_1000.csv")
print(f"Shape: {df.shape}")

preprocessed/imdb_top_1000.csv
Shape: (1000, 13)

# preprocessed bolgan dataset bilan davom etdim

In [471]:
# preprocessed papkadan tayyor datasetni import qilib olish 
df = pd.read_csv("preprocessed\imdb_top_1000.csv")

In [472]:
# malumot olish 
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Released_Year  1000 non-null   int64
 1   Certificate    1000 non-null   int64
 2   Runtime        1000 non-null   int64
 3   Genre          1000 non-null   int64
 4   IMDB_Rating    1000 non-null   float64
 5   Meta_score     1000 non-null   float64
 6   Director       1000 non-null   int64
 7   Star1          1000 non-null   int64
 8   Star2          1000 non-null   int64
 9   Star3          1000 non-null   int64
 10  Star4          1000 non-null   int64
 11  No_of_Votes    1000 non-null   int64
 12  Gross          1000 non-null   float64
dtypes: float64(3), int64(10)
memory usage: 101.7 KB

# Algorithms + K-fold validation

In [473]:
import pandas as pd
import xgboost as xgb
from tabulate import tabulate
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_absolute_error, mean_squared_error

X = df.select_dtypes(include=['int64', 'float64']).drop(['Sale_ID'], axis=1, errors='ignore')
y = df['IMDB_Rating']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree": DecisionTreeRegressor(random_state=42),
    "Random Forest": RandomForestRegressor(n_estimators=100, random_state=42),
    "SVM (SVR)": SVR(kernel='rbf'),
    "XGBoost": xgb.XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42)
}

results = []

for name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    
    score = model.score(X_test, y_test)
    mae = mean_absolute_error(y_test, predictions)
    mse = mean_squared_error(y_test, predictions)
    
    results.append([name, f"{score:.4f}", f"{mae:.4f}", f"{mse:.4f}"])

headers = ["Model", "R2 Score", "MAE", "MSE"]
print(tabulate(results, headers=headers, tablefmt="grid"))

+-------------------+------------+--------+--------+
| Model             |   R2 Score |    MAE |    MSE |
+===================+============+========+========+
| Linear Regression |     1      | 0      | 0      |
+-------------------+------------+--------+--------+
| Decision Tree     |     1      | 0      | 0      |
+-------------------+------------+--------+--------+
| Random Forest     |     1      | 0.0001 | 0      |
+-------------------+------------+--------+--------+
| SVM (SVR)         |    -0.0071 | 0.2064 | 0.0646 |
+-------------------+------------+--------+--------+
| XGBoost           |     1      | 0      | 0      |
+-------------------+------------+--------+--------+

In [474]:
# K-fold cross validation
from sklearn.model_selection import KFold, cross_val_score

kf = KFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(model, x,y,cv=kf, scoring="r2")
print(scores.mean())

from sklearn.metrics import make_scorer

mae=make_scorer(mean_absolute_error,greater_is_better=False)
scores=cross_val_score(model,x,y,cv=kf,scoring=mae)
print(-scores)

0.998747480387796
[3.12466621e-05 2.64121675e-03 3.03139687e-05 3.53517532e-05
 1.69959831e-03]