# Data bn tanishuv va Preprocessing

In [4]:
import pandas as pd 
df=pd.read_csv('student_performance.csv')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            500 non-null    str
 1   gender                500 non-null    str
 2   age                   500 non-null    int64
 3   study_hours_per_week  500 non-null    int64
 4   attendance_rate       500 non-null    float64
 5   parent_education      383 non-null    str
 6   internet_access       500 non-null    str
 7   extracurricular       500 non-null    str
 8   previous_score        500 non-null    int64
 9   final_score           500 non-null    int64
 10  passed                500 non-null    str
dtypes: float64(1), int64(4), str(6)
memory usage: 43.1 KB

In [6]:
df.isnull().sum()

student_id                0
gender                    0
age                       0
study_hours_per_week      0
attendance_rate           0
parent_education        117
internet_access           0
extracurricular           0
previous_score            0
final_score               0
passed                    0
dtype: int64

In [10]:
df['parent_education'] = df['parent_education'].fillna('Unknown')

In [13]:
df.isnull().sum()

student_id              0
gender                  0
age                     0
study_hours_per_week    0
attendance_rate         0
parent_education        0
internet_access         0
extracurricular         0
previous_score          0
final_score             0
passed                  0
dtype: int64

In [11]:
df.sample(10)

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
459,STU0460,Female,19,18,68.7,High School,Yes,Yes,93,55,Yes
428,STU0429,Male,18,12,81.6,Bachelor,No,Yes,30,47,No
257,STU0258,Female,19,21,88.6,Master,Yes,No,48,73,Yes
107,STU0108,Female,15,29,92.3,High School,No,Yes,48,78,Yes
464,STU0465,Female,18,21,95.8,Bachelor,No,No,73,68,Yes
144,STU0145,Female,19,9,90.4,Unknown,Yes,No,33,37,No
456,STU0457,Male,15,27,80.2,Unknown,No,Yes,88,77,Yes
285,STU0286,Female,15,26,80.9,Bachelor,Yes,Yes,64,65,Yes
325,STU0326,Male,18,18,87.5,Master,No,No,71,70,Yes
293,STU0294,Female,18,12,71.5,Unknown,Yes,No,71,57,Yes

# Preprocessing

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   student_id            500 non-null    str
 1   gender                500 non-null    str
 2   age                   500 non-null    int64
 3   study_hours_per_week  500 non-null    int64
 4   attendance_rate       500 non-null    float64
 5   parent_education      500 non-null    str
 6   internet_access       500 non-null    str
 7   extracurricular       500 non-null    str
 8   previous_score        500 non-null    int64
 9   final_score           500 non-null    int64
 10  passed                500 non-null    str
dtypes: float64(1), int64(4), str(6)
memory usage: 43.1 KB

In [15]:
from sklearn.preprocessing import LabelEncoder
def encodla(df):
    encoder=LabelEncoder()
    for col in df.columns:
        if df[col].dtype=='str':
            if df[col].nunique()<=5:
                dummies=pd.get_dummies(df[col],prefix=col,dtype=int)
                df=pd.concat([df.drop(columns=col),dummies],axis=1)
            else:
                df[col]=encoder.fit_transform(df[col])
    return df

In [16]:
df=encodla(df)

In [17]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   student_id                    500 non-null    int64
 1   age                           500 non-null    int64
 2   study_hours_per_week          500 non-null    int64
 3   attendance_rate               500 non-null    float64
 4   previous_score                500 non-null    int64
 5   final_score                   500 non-null    int64
 6   gender_Female                 500 non-null    int64
 7   gender_Male                   500 non-null    int64
 8   parent_education_Bachelor     500 non-null    int64
 9   parent_education_High School  500 non-null    int64
 10  parent_education_Master       500 non-null    int64
 11  parent_education_PhD          500 non-null    int64
 12  parent_education_Unknown      500 non-null    int64
 13  internet_access_No            500 non-null    int64
 14  internet_access_Yes           500 non-null    int64
 15  extracurricular_No            500 non-null    int64
 16  extracurricular_Yes           500 non-null    int64
 17  passed_No                     500 non-null    int64
 18  passed_Yes                    500 non-null    int64
dtypes: float64(1), int64(18)
memory usage: 74.3 KB

# Scaling

In [18]:
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()

In [19]:
def scaling_qil(df):
    num_col = df.select_dtypes(include=['int64','float64']).columns
    df[num_col]=scaler.fit_transform(df[num_col]) 
    return df

In [20]:
df=scaling_qil(df)

In [23]:
df.sample(15)

,student_id,age,study_hours_per_week,attendance_rate,previous_score,final_score,gender_Female,gender_Male,parent_education_Bachelor,parent_education_High School,parent_education_Master,parent_education_PhD,parent_education_Unknown,internet_access_No,internet_access_Yes,extracurricular_No,extracurricular_Yes,passed_No,passed_Yes
164,0.328657,0.75,0.857143,0.335341,0.123077,0.546667,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
210,0.420842,0.25,0.357143,0.604418,0.784615,0.360000,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0
199,0.398798,1.00,0.607143,0.287149,0.707692,0.586667,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
270,0.541082,1.00,0.535714,0.180723,0.138462,0.493333,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0
413,0.827655,0.50,0.178571,0.837349,0.046154,0.280000,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
357,0.715431,0.00,0.035714,0.921687,0.892308,0.506667,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0
251,0.503006,0.00,0.750000,0.963855,0.230769,0.560000,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
60,0.120240,0.25,0.928571,0.417671,0.938462,0.613333,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0
277,0.555110,1.00,0.535714,0.052209,0.969231,0.493333,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0
417,0.835671,0.50,0.214286,0.463855,0.000000,0.266667,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0
126,0.252505,0.00,0.250000,0.887550,0.723077,0.573333,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0
122,0.244489,0.75,0.964286,0.803213,0.015385,0.653333,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0
345,0.691383,0.00,0.000000,0.706827,0.676923,0.320000,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0
352,0.705411,0.25,0.250000,0.803213,0.907692,0.426667,0.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0
147,0.294589,0.50,0.821429,0.321285,0.292308,0.493333,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,1.0